WITH CONSULTA AS (
    SELECT 
        LOCALIDADE = COALESCE(CF.UF, CF.REGIAO_GEOGRAFICA, 'Brasil'),
        NUM_ATRACACOES = COUNT(*),
        TEMPO_ATRACADO = AVG(DATEDIFF(HOUR, DATA_ATRACACAO, DATA_DESATRACACAO)),
        TEMPO_ESPERA = AVG(DATEDIFF(HOUR, DATA_CHEGADA, DATA_ATRACACAO)),
        MES = UPPER(CF.MES),
        NUM_MES = DATEPART(MONTH, DATA_DESATRACACAO),
        ANO = CF.ANO
    FROM ATRACACAO_FATO CF
    WHERE CF.SGUF = 'CE' OR CF.REGIAO_GEOGRAFICA = 'NORDESTE' OR CF.SGUF IS NOT NULL
    GROUP BY COALESCE(CF.UF, CF.REGIAO_GEOGRAFICA, 'Brasil'), CF.MES, CF.ANO, DATEPART(MONTH, DATA_DESATRACACAO)
)
SELECT  
    A.LOCALIDADE,
    [NÚMERO DE ATRACAÇÕES] = A.NUM_ATRACACOES,
    [VARIAÇÃO PERC%] = ISNULL(CAST((A.NUM_ATRACACOES / B.NUM_ATRACACOES - 1) * 100.0 AS NUMERIC(5,2)), 0),
    [TEMPO ATRACADO MÉDIO (H)] = A.TEMPO_ATRACADO,
    [TEMPO DE ESPERA MÉDIO (H)] = A.TEMPO_ESPERA,
    A.MES,
    A.ANO
FROM CONSULTA A
LEFT JOIN CONSULTA B ON A.LOCALIDADE = B.LOCALIDADE AND A.NUM_MES = B.NUM_MES AND A.ANO - 1 = B.ANO
WHERE A.ANO IN (2021, 2023)
ORDER BY A.LOCALIDADE, A.ANO, A.NUM_MES;